Import Numpy as np and run it

Reshape this array to be a multi dimentaional array with 2 sets of 4 numbers and print the result

In [4]:
my_array = np.array([2,2,2,2,4,4,4,4])


Reshape the same array to be 4 sets of two numbers and print the result

In [ ]:
my_array = np.array([2,2,2,2,4,4,4,4])


[[2 2]
 [2 2]
 [4 4]
 [4 4]]


Multiply each element of this array by 2 and print the result. Use numpy, not a for loop

In [ ]:
my_array = np.array([2,2,2,2,4,4,4,4])


[4 4 4 4 8 8 8 8]


Add each element of these arrays together in a new array called new_array, don't use a for loop, use numpy. Print the result

In [ ]:
array1 = np.array([6,4,31,4,5,7,3,1])
array2 = np.array([3,2,6,3,1,5,7,8])



[ 18   8 186  12   5  35  21   8]


Save a CSV file with the array below called "my_CSV" with the headers "ones, tens, hundreds". The columns should only contain numbers that correspond to the header.

In [ ]:
data_set_1 = np.array([[1, 10, 100],[2, 20, 200],[3, 30, 300]])


Convert the array below to match data_set_1 using numpy. Print the result.

In [ ]:
data_set_a = np.array([1, 10, 100,2, 20, 200, 3, 30, 300])

[[  1  10 100]
 [  2  20 200]
 [  3  30 300]]


Create two numpy arrays, one with even numbers and one with odd numbers. Make a CSV fle called even_and_odd where even and odd numbers are in different columns (not rows). Label each one with the appropriate header.

Write a peice of code that asks the user for a number. Create two numpy arrays:
first_array should contain the 10 numbers after that number
second_array should count up 2 10 times, then multiply the entire array by 2

Combine the two arrays into super_array. Reshape super_array to be sets of 5 numbers
print the result

What is the number?2
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11  4  8]
 [12 16 20 24]
 [28 32 36 40]]
